# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    # branches: [ "master", "dev" ]
  pull_request:
    # branches: [ "master", "dev" ]
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        target-framework: [ 'net6.0', 'net7.0', 'net8.0']
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      # with:
      #   # dotnet-version: ${{ matrix.dotnet-version }}
      #   dotnet-version: |
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build and Test ${{ matrix.target-framework }}
      run: dotnet build --no-restore --configuration Release --framework ${{ matrix.target-framework }}

    - name: Run Tests ${{ matrix.target-framework }}
      if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/dev') || startsWith(github.ref, 'refs/heads/test')
      run: dotnet test --no-build --verbosity normal --framework ${{ matrix.target-framework }}